### ISSUE TITLE
dataset을 만들때 해당글자간 밸류가 같아야 하나요??

### ISSUE THREAD

**Issue by KarlBee** [jeina7/Handwriting_styler#1]
dataset을 만들고 있는데, 글꼴별로 제공하는 글자수 차이가 있어서그런지, 저장할때 count로 제목을 저장시키는데  예를그러 '얌'자가 어떤글자체에선 1108번이고 다른글자체에선 850번이면 나중에 문제가 생기나요?

**Comment by jeina7** [comment]
중요한 것은 source image와 target image가 붙어있는 128x256 크기의 dataset을 만들 때 고딕체의 "얌"과 특정폰트의 "얌"이 제대로 붙어있는 것이기 때문에, value number가 다른 것은 상관 없습니다. 
데이터셋을 만들 때 서로 쌍이 되어주는 고딕체 이미지와 폰트 이미지가 잘 붙어서 생성되기만 하면 되겠죠!
